# Generated by Django 5.2.4 on 2025-08-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='receipt_id')),
                ('user_id', models.IntegerField(verbose_name='user_id')),
                ('campaign_id', models.IntegerField(verbose_name='campaign_id')),
                ('image_path', models.ImageField(upload_to='raw_image/')),
                ('detection', models.JSONField(blank=True, null=True)),
                ('parsed_data', models.JSONField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
