# Generated by Django 5.2.4 on 2025-07-31 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('line_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='receipt_id')),
                ('image_path', models.ImageField(upload_to='raw_image/')),
                ('detection', models.JSONField(blank=True, null=True)),
                ('parsed_data', models.JSONField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_receipt', to='line_app.campaign')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_receipt', to='line_app.user')),
            ],
        ),
    ]
