# Generated by Django 5.2.4 on 2025-08-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='campaign_id',
            field=models.IntegerField(verbose_name='campaign_id'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='user_id',
            field=models.IntegerField(verbose_name='user_id'),
        ),
    ]
