# Generated by Django 5.2.4 on 2025-08-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='campaign_id')),
                ('name', models.CharField(max_length=255, verbose_name='campaign_name')),
                ('benefit_type', models.CharField()),
                ('benefit_value', models.ImageField(upload_to='')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('describtion', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='user_id')),
                ('line_user_id', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('campaign_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
